# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Testing The Pipelines"
  displayName: 'pipeline Tesing'

- script: echo $(Build.BuildID)
  displayName: 'Display The Build-ID'

- script: ls -al && pwd
  displayName: 'List Files & current working Directory'

- script: sudo apt update && sudo apt install -y openjdk-8-jdk && java -version
  displayName: 'Installing openjdk 8 and check Javaversion'

- script: ls -al && chmod 700 build.sh && sudo bash ./build.sh && ls -al
  displayName: 'Run the build script'
  
- script: ls -al && mv ROOT.WAR ROOT$(Build.BuildID).war && ls -al
  displayName: 'List Files & Rename Root.war'
  
- task: CopyFiles@2
  inputs:
    contents: 'ROOT$(Build.BuildID).war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    overwrite: true
  displayName: 'copying WAR file to ArtifactStagingDirectory)'
  
- script: ls -al $(Build.ArtifactStagingDirectory)
  displayName: 'List Build Artifact Staging Folder'
